import { Button } from '@chakra-ui/react'
import Head from 'next/head'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Home</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main>
                <p>main</p>
                <Button colorScheme={'blue'}>Hello</Button>
            </main>
        </div>
    )
}
